import type { Instrument, RiskBucket } from "./types";

/**
 * Development instrument universe (mock market-data API).
 * Figures are illustrative long-run estimates for simulation only.
 */
export const INSTRUMENT_UNIVERSE: Instrument[] = [
  // ---------------- LOW RISK ----------------
  {
    id: "liq-fund",
    name: "Overnight & Liquid Debt Fund",
    symbol: "LIQUID",
    bucket: "low",
    assetClass: "Cash & Equivalents",
    sector: "Money Market",
    expectedReturn: 0.066,
    volatility: 0.008,
    beta: 0.01,
    liquidityScore: 1,
    valuationScore: 0.7,
    historicalMaxDrawdown: 0.002,
    cagr3y: 0.063,
    equitySensitivity: 0,
    ratesSensitivity: 0.1,
    notes: "T+1 redemption, primary liquidity sleeve.",
  },
  {
    id: "gsec-10y",
    name: "Government Securities Fund (10Y)",
    symbol: "GSEC10",
    bucket: "low",
    assetClass: "Sovereign Debt",
    sector: "Government",
    expectedReturn: 0.073,
    volatility: 0.045,
    beta: -0.05,
    liquidityScore: 0.9,
    valuationScore: 0.8,
    historicalMaxDrawdown: 0.06,
    cagr3y: 0.068,
    equitySensitivity: 0,
    ratesSensitivity: 6.8,
    notes: "Zero credit risk, duration-sensitive, equity hedge.",
  },
  {
    id: "corp-bond-aaa",
    name: "AAA Corporate Bond Fund",
    symbol: "AAACORP",
    bucket: "low",
    assetClass: "Corporate Debt",
    sector: "Financials",
    expectedReturn: 0.078,
    volatility: 0.035,
    beta: 0.06,
    liquidityScore: 0.85,
    valuationScore: 0.75,
    historicalMaxDrawdown: 0.045,
    cagr3y: 0.071,
    equitySensitivity: 0.05,
    ratesSensitivity: 4.2,
    notes: "High-grade accrual, spread over sovereign.",
  },
  {
    id: "banking-psu",
    name: "Banking & PSU Debt Fund",
    symbol: "BPSU",
    bucket: "low",
    assetClass: "Corporate Debt",
    sector: "Financials",
    expectedReturn: 0.075,
    volatility: 0.03,
    beta: 0.05,
    liquidityScore: 0.88,
    valuationScore: 0.72,
    historicalMaxDrawdown: 0.038,
    cagr3y: 0.069,
    equitySensitivity: 0.04,
    ratesSensitivity: 3.4,
    notes: "Quasi-sovereign credit, moderate duration.",
  },
  {
    id: "arbitrage",
    name: "Arbitrage Fund",
    symbol: "ARBI",
    bucket: "low",
    assetClass: "Market Neutral",
    sector: "Derivatives",
    expectedReturn: 0.069,
    volatility: 0.015,
    beta: 0.03,
    liquidityScore: 0.92,
    valuationScore: 0.68,
    historicalMaxDrawdown: 0.01,
    cagr3y: 0.066,
    equitySensitivity: 0.02,
    ratesSensitivity: 0.3,
    notes: "Cash-futures spread capture, equity taxation.",
  },
  {
    id: "target-mat-2030",
    name: "Target Maturity Index Fund 2030",
    symbol: "TMF30",
    bucket: "low",
    assetClass: "Sovereign Debt",
    sector: "Government",
    expectedReturn: 0.074,
    volatility: 0.028,
    beta: -0.02,
    liquidityScore: 0.8,
    valuationScore: 0.82,
    historicalMaxDrawdown: 0.032,
    cagr3y: 0.07,
    equitySensitivity: 0,
    ratesSensitivity: 4.6,
    notes: "Roll-down structure, visibility on maturity yield.",
  },
  {
    id: "gold-etf",
    name: "Gold ETF",
    symbol: "GOLD",
    bucket: "low",
    assetClass: "Commodities",
    sector: "Precious Metals",
    expectedReturn: 0.085,
    volatility: 0.135,
    beta: -0.12,
    liquidityScore: 0.9,
    valuationScore: 0.6,
    historicalMaxDrawdown: 0.19,
    cagr3y: 0.126,
    equitySensitivity: -0.15,
    ratesSensitivity: 0.8,
    notes: "Crisis diversifier, negative equity correlation.",
  },

  // ---------------- MODERATE RISK ----------------
  {
    id: "nifty50-idx",
    name: "Nifty 50 Index Fund",
    symbol: "NIFTY50",
    bucket: "moderate",
    assetClass: "Large-Cap Equity",
    sector: "Diversified",
    expectedReturn: 0.121,
    volatility: 0.155,
    beta: 1,
    liquidityScore: 0.98,
    valuationScore: 0.62,
    historicalMaxDrawdown: 0.38,
    cagr3y: 0.142,
    equitySensitivity: 1,
    ratesSensitivity: 0.6,
    notes: "Core beta exposure, lowest cost, deep liquidity.",
  },
  {
    id: "hybrid-aggr",
    name: "Aggressive Hybrid Fund (65/35)",
    symbol: "HYBRID",
    bucket: "moderate",
    assetClass: "Hybrid",
    sector: "Diversified",
    expectedReturn: 0.108,
    volatility: 0.105,
    beta: 0.66,
    liquidityScore: 0.9,
    valuationScore: 0.7,
    historicalMaxDrawdown: 0.24,
    cagr3y: 0.118,
    equitySensitivity: 0.65,
    ratesSensitivity: 2.1,
    notes: "Built-in rebalancing between equity and debt.",
  },
  {
    id: "nifty-next50",
    name: "Nifty Next 50 Index Fund",
    symbol: "JUNIOR",
    bucket: "moderate",
    assetClass: "Large-Cap Equity",
    sector: "Diversified",
    expectedReturn: 0.132,
    volatility: 0.195,
    beta: 1.12,
    liquidityScore: 0.92,
    valuationScore: 0.55,
    historicalMaxDrawdown: 0.44,
    cagr3y: 0.171,
    equitySensitivity: 1.1,
    ratesSensitivity: 0.7,
    notes: "Emerging large caps, higher dispersion than Nifty 50.",
  },
  {
    id: "dividend-yield",
    name: "Dividend Yield Equity Fund",
    symbol: "DIVYLD",
    bucket: "moderate",
    assetClass: "Large-Cap Equity",
    sector: "Value",
    expectedReturn: 0.115,
    volatility: 0.142,
    beta: 0.86,
    liquidityScore: 0.86,
    valuationScore: 0.78,
    historicalMaxDrawdown: 0.31,
    cagr3y: 0.155,
    equitySensitivity: 0.88,
    ratesSensitivity: 0.9,
    notes: "Cash-flow tilt, defensive in drawdowns.",
  },
  {
    id: "intl-dev-eq",
    name: "Developed Markets Equity FoF",
    symbol: "GLOBAL",
    bucket: "moderate",
    assetClass: "International Equity",
    sector: "Global",
    expectedReturn: 0.118,
    volatility: 0.163,
    beta: 0.42,
    liquidityScore: 0.75,
    valuationScore: 0.58,
    historicalMaxDrawdown: 0.34,
    cagr3y: 0.147,
    equitySensitivity: 0.6,
    ratesSensitivity: 0.5,
    notes: "Currency + geography diversification vs India beta.",
  },
  {
    id: "reit-basket",
    name: "Listed REIT Basket",
    symbol: "REIT",
    bucket: "moderate",
    assetClass: "Real Estate",
    sector: "Real Estate",
    expectedReturn: 0.101,
    volatility: 0.128,
    beta: 0.58,
    liquidityScore: 0.7,
    valuationScore: 0.74,
    historicalMaxDrawdown: 0.27,
    cagr3y: 0.089,
    equitySensitivity: 0.55,
    ratesSensitivity: 3.2,
    notes: "Rental yield, rate-sensitive, low equity overlap.",
  },
  {
    id: "eq-savings",
    name: "Equity Savings Fund",
    symbol: "EQSAV",
    bucket: "moderate",
    assetClass: "Hybrid",
    sector: "Diversified",
    expectedReturn: 0.092,
    volatility: 0.072,
    beta: 0.38,
    liquidityScore: 0.88,
    valuationScore: 0.71,
    historicalMaxDrawdown: 0.14,
    cagr3y: 0.096,
    equitySensitivity: 0.35,
    ratesSensitivity: 1.6,
    notes: "Equity + arbitrage + debt; drawdown controlled.",
  },

  // ---------------- HIGH RISK ----------------
  {
    id: "midcap-idx",
    name: "Nifty Midcap 150 Index Fund",
    symbol: "MIDCAP",
    bucket: "high",
    assetClass: "Mid-Cap Equity",
    sector: "Diversified",
    expectedReturn: 0.145,
    volatility: 0.225,
    beta: 1.24,
    liquidityScore: 0.85,
    valuationScore: 0.45,
    historicalMaxDrawdown: 0.52,
    cagr3y: 0.213,
    equitySensitivity: 1.25,
    ratesSensitivity: 0.9,
    notes: "Earnings growth premium, elevated valuations.",
  },
  {
    id: "smallcap-idx",
    name: "Nifty Smallcap 250 Index Fund",
    symbol: "SMALLCAP",
    bucket: "high",
    assetClass: "Small-Cap Equity",
    sector: "Diversified",
    expectedReturn: 0.155,
    volatility: 0.28,
    beta: 1.38,
    liquidityScore: 0.7,
    valuationScore: 0.38,
    historicalMaxDrawdown: 0.63,
    cagr3y: 0.229,
    equitySensitivity: 1.4,
    ratesSensitivity: 1,
    notes: "Highest drawdown history, impact costs in stress.",
  },
  {
    id: "tech-sector",
    name: "IT / Technology Sector Fund",
    symbol: "ITSEC",
    bucket: "high",
    assetClass: "Sector Equity",
    sector: "Technology",
    expectedReturn: 0.138,
    volatility: 0.242,
    beta: 1.05,
    liquidityScore: 0.9,
    valuationScore: 0.52,
    historicalMaxDrawdown: 0.48,
    cagr3y: 0.126,
    equitySensitivity: 1.15,
    ratesSensitivity: 1.4,
    notes: "Export earnings, USD-linked, concentrated sector risk.",
  },
  {
    id: "bank-sector",
    name: "Banking & Financial Services Fund",
    symbol: "BANKSEC",
    bucket: "high",
    assetClass: "Sector Equity",
    sector: "Financials",
    expectedReturn: 0.134,
    volatility: 0.228,
    beta: 1.18,
    liquidityScore: 0.93,
    valuationScore: 0.66,
    historicalMaxDrawdown: 0.51,
    cagr3y: 0.134,
    equitySensitivity: 1.2,
    ratesSensitivity: 2.2,
    notes: "Credit-cycle leveraged, rate-sensitive.",
  },
  {
    id: "em-equity",
    name: "Emerging Markets Equity FoF",
    symbol: "EMEQ",
    bucket: "high",
    assetClass: "International Equity",
    sector: "Global",
    expectedReturn: 0.128,
    volatility: 0.212,
    beta: 0.55,
    liquidityScore: 0.68,
    valuationScore: 0.69,
    historicalMaxDrawdown: 0.46,
    cagr3y: 0.081,
    equitySensitivity: 0.75,
    ratesSensitivity: 0.6,
    notes: "Diversifies India-specific risk within growth sleeve.",
  },
  {
    id: "thematic-infra",
    name: "Infrastructure Thematic Fund",
    symbol: "INFRA",
    bucket: "high",
    assetClass: "Sector Equity",
    sector: "Industrials",
    expectedReturn: 0.142,
    volatility: 0.256,
    beta: 1.31,
    liquidityScore: 0.72,
    valuationScore: 0.41,
    historicalMaxDrawdown: 0.58,
    cagr3y: 0.242,
    equitySensitivity: 1.35,
    ratesSensitivity: 1.8,
    notes: "Capex cycle proxy, cyclical and policy dependent.",
  },
  {
    id: "momentum-factor",
    name: "Nifty 200 Momentum 30 Index Fund",
    symbol: "MOMENT",
    bucket: "high",
    assetClass: "Factor Equity",
    sector: "Diversified",
    expectedReturn: 0.149,
    volatility: 0.238,
    beta: 1.21,
    liquidityScore: 0.82,
    valuationScore: 0.43,
    historicalMaxDrawdown: 0.49,
    cagr3y: 0.226,
    equitySensitivity: 1.28,
    ratesSensitivity: 0.8,
    notes: "Trend factor, sharp reversals at regime turns.",
  },
];

export function universeFor(bucket: RiskBucket): Instrument[] {
  return INSTRUMENT_UNIVERSE.filter((i) => i.bucket === bucket);
}

export function findInstrument(id: string): Instrument | undefined {
  return INSTRUMENT_UNIVERSE.find((i) => i.id === id);
}